#pragma once

#define SERIAL_USART_FULL_DUPLEX
#define SERIAL_USART_TX_PIN GP8
#define SERIAL_USART_RX_PIN GP9
#define SERIAL_USART_PIN_SWAP
#define SERIAL_PIO_USE_PIO1
#define EE_HANDS
#define SPLIT_USB_TIMEOUT 8000
#define SPLIT_USB_DETECT
#define SPLIT_TRANSPORT_MIRROR

#define ANALOG_JOYSTICK_X_AXIS_PIN GP26
#define ANALOG_JOYSTICK_Y_AXIS_PIN GP27
#define ANALOG_JOYSTICK_AUTO_AXIS
#define ANALOG_JOYSTICK_CUTOFF
#define SPLIT_POINTING_ENABLE
#define POINTING_DEVICE_COMBINED
#define POINTING_DEVICE_INVERT_X_RIGHT
#define POINTING_DEVICE_INVERT_Y_RIGHT
#define POINTING_DEVICE_INVERT_X

#define POINTING_DEVICE_TASK_THROTTLE_MS 10

#define ANALOG_JOYSTICK_SPEED_MAX 3
#define ANALOG_JOYSTICK_SPEED_REGULATOR 24